// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.POSTGRES_PRISMA_URL || process.env.NEON_DB_POSTGRES_PRISMA_URL || process.env.DATABASE_URL || process.env.NEON_DB_DATABASE_URL,
  },
});
